import pandas as pd

# List of dictionaries containing movie details
movies_data =[
    {"title": "The Shawshank Redemption", "genres": "Motivational", "overview": "A prisoner escapes prison after years of careful planning."},
    {"title": "Inception", "genres": "Sci-Fi/Thriller", "overview": "A thief infiltrates dreams to implant an idea in someone's mind."},
    {"title": "The Dark Knight", "genres": "Action/Crime", "overview": "Batman fights the Joker to save Gotham City."},
    {"title": "Forrest Gump", "genres": "Drama/Motivational", "overview": "A man's simple life turns into extraordinary adventures."},
    {"title": "The Godfather", "genres": "Crime/Drama", "overview": "A mafia boss passes his empire to his reluctant son."},
    {"title": "Interstellar", "genres": "Sci-Fi/Adventure", "overview": "A team of explorers travel through a wormhole to find a new home for humanity."},
    {"title": "The Lion King", "genres": "Animation/Adventure", "overview": "A lion prince overcomes adversity to reclaim his throne."},
    {"title": "Gladiator", "genres": "Action/Drama", "overview": "A betrayed general seeks revenge in the Roman Empire."},
    {"title": "Titanic", "genres": "Romance/Drama", "overview": "A young couple's love blossoms on the doomed ocean liner."},
    {"title": "Schindler's List", "genres": "Historical/Drama", "overview": "A businessman saves Jews during the Holocaust."},
    {"title": "The Matrix", "genres": "Sci-Fi/Action", "overview": "A hacker discovers the true nature of his reality."},
    {"title": "The Avengers", "genres": "Action/Adventure", "overview": "Earth’s mightiest heroes team up to fight an alien invasion."},
    {"title": "Saving Private Ryan", "genres": "War/Drama", "overview": "A squad is sent to rescue a soldier during WWII."},
    {"title": "Toy Story", "genres": "Animation/Comedy", "overview": "Toys come to life when humans aren't around."},
    {"title": "The Silence of the Lambs", "genres": "Thriller/Crime", "overview": "An FBI trainee seeks the help of a cannibal to catch a serial killer."},
    {"title": "Pulp Fiction", "genres": "Crime/Comedy", "overview": "Interweaving stories of crime and redemption."},
    {"title": "The Pursuit of Happyness", "genres": "Motivational/Drama", "overview": "A man struggles to provide for his son and pursue his dreams."},
    {"title": "The Grand Budapest Hotel", "genres": "Comedy/Drama", "overview": "A concierge and his protégé become embroiled in a heist."},
    {"title": "The Sixth Sense", "genres": "Horror/Thriller", "overview": "A boy who can see ghosts is helped by a psychologist."},
    {"title": "Parasite", "genres": "Thriller/Drama", "overview": "A poor family infiltrates a wealthy household."},
    {"title": "Jurassic Park", "genres": "Adventure/Sci-Fi", "overview": "Dinosaurs are brought back to life in a theme park."},
    {"title": "Fight Club", "genres": "Drama/Thriller", "overview": "A man starts a secret club that spirals out of control."},
    {"title": "The Notebook", "genres": "Romance/Drama", "overview": "A love story that withstands the test of time."},
    {"title": "Finding Nemo", "genres": "Animation/Adventure", "overview": "A clownfish searches the ocean for his lost son."},
    {"title": "Avengers: Endgame", "genres": "Action/Sci-Fi", "overview": "The Avengers attempt to reverse the damage caused by Thanos."},
    {"title": "Black Panther", "genres": "Action/Adventure", "overview": "A king must defend his kingdom from a powerful adversary."},
    {"title": "Django Unchained", "genres": "Western/Drama", "overview": "A freed slave seeks revenge in the Old West."},
    {"title": "The Social Network", "genres": "Biography/Drama", "overview": "The story of the creation of Facebook."},
    {"title": "La La Land", "genres": "Musical/Romance", "overview": "Two aspiring artists navigate love and ambition in Los Angeles."},
    {"title": "Braveheart", "genres": "Historical/Drama", "overview": "A Scotsman leads a rebellion against England."},
    {"title": "The Departed", "genres": "Crime/Thriller", "overview": "An undercover cop and a mole struggle within the police and mob."},
    {"title": "Mad Max: Fury Road", "genres": "Action/Adventure", "overview": "Survivors fight for survival in a post-apocalyptic desert."},
    {"title": "The Green Mile", "genres": "Drama/Fantasy", "overview": "A death row guard encounters a man with healing powers."},
    {"title": "A Beautiful Mind", "genres": "Biography/Drama", "overview": "The story of a brilliant mathematician with schizophrenia."},
    {"title": "Cast Away", "genres": "Drama/Adventure", "overview": "A man stranded on an island struggles for survival."},
    {"title": "Iron Man", "genres": "Action/Sci-Fi", "overview": "A billionaire builds a high-tech suit to save the world."},
    {"title": "The Exorcist", "genres": "Horror", "overview": "A mother seeks help for her possessed daughter."},
    {"title": "The Prestige", "genres": "Mystery/Thriller", "overview": "Rival magicians attempt to outdo each other."},
    {"title": "Goodfellas", "genres": "Crime/Drama", "overview": "The life story of a gangster in the mafia."},
    {"title": "12 Years a Slave", "genres": "Biography/Drama", "overview": "A free man is kidnapped into slavery."},
    {"title": "Her", "genres": "Sci-Fi/Romance", "overview": "A man falls in love with an AI operating system."},
    {"title": "The Revenant", "genres": "Adventure/Drama", "overview": "A frontiersman seeks vengeance after being left for dead."},
    {"title": "The Big Lebowski", "genres": "Comedy", "overview": "A slacker gets entangled in a mistaken identity case."},
    {"title": "Whiplash", "genres": "Drama", "overview": "A young drummer is pushed to his limits by an abusive instructor."},
    {"title": "Spider-Man: Into the Spider-Verse", "genres": "Animation/Action", "overview": "Teenagers from different dimensions team up."},
    {"title": "Logan", "genres": "Action/Drama", "overview": "A weary Wolverine cares for ailing Professor X in a dystopian future."},
    {"title": "Coco", "genres": "Animation/Fantasy", "overview": "A boy discovers his family's heritage in the Land of the Dead."},
    {"title": "Get Out", "genres": "Horror/Thriller", "overview": "A man uncovers dark secrets while visiting his girlfriend’s family."},
    {"title": "The Truman Show", "genres": "Comedy/Drama", "overview": "A man discovers his life is a reality show."},
    {"title": "The Wolf of Wall Street", "genres": "Biography/Comedy", "overview": "The rise and fall of a stockbroker."},
    {"title": "Harry Potter and the Philosopher's Stone", "genres": "Fantasy/Adventure", "overview": "A young boy discovers he's a wizard."},
    {"title": "Joker", "genres": "Drama/Crime", "overview": "A troubled man becomes Gotham’s infamous villain."},
    {"title": "Slumdog Millionaire", "genres": "Drama/Romance", "overview": "A young man from Mumbai reflects on his life."},
    {"title": "The Great Gatsby", "genres": "Drama/Romance", "overview": "A man pursues the American Dream with tragic results."},
    {"title": "Deadpool", "genres": "Comedy/Action", "overview": "An anti-hero with a twisted sense of humor seeks revenge."},
    {"title": "Amélie", "genres": "Romance/Comedy", "overview": "A quirky woman impacts the lives of people around her."},
    {"title": "The Conjuring", "genres": "Horror", "overview": "Paranormal investigators help a family in a haunted house."},
    {"title": "The Hateful Eight", "genres": "Western/Drama", "overview": "Strangers seek refuge in a remote cabin during a blizzard."},
    {"title": "Inside Out", "genres": "Animation/Family", "overview": "A young girl's emotions come to life."},
    {"title": "Shutter Island", "genres": "Thriller/Mystery", "overview": "A detective investigates a psychiatric hospital."},
    {"title": "Sholay", "genres": "Action/Drama", "overview": "Two criminals are hired to capture a notorious dacoit."},
    {"title": "Dilwale Dulhania Le Jayenge", "genres": "Romance/Drama", "overview": "A young man and woman fall in love on a European vacation."},
    {"title": "Gully Boy", "genres": "Musical/Drama", "overview": "A young man from the slums pursues his dream of becoming a rapper."},
    {"title": "Raazi", "genres": "Spy Thriller", "overview": "A young Indian woman marries a Pakistani army officer to spy during the 1971 Indo-Pak war."},
    {"title": "Zindagi Na Milegi Dobara", "genres": "Adventure/Drama", "overview": "Three friends embark on a road trip across Spain to fulfill their travel bucket list."},
    {"title": "Piku", "genres": "Comedy/Drama", "overview": "A road trip brings a father and daughter closer, despite his constant complaints about health."},
    {"title": "Baahubali: The Beginning", "genres": "Fantasy/Action", "overview": "The journey of a young man discovering his royal legacy and avenging his father's murder."},
    {"title": "Barfi!", "genres": "Romantic/Comedy", "overview": "The story of a mute man who finds love in the most unexpected circumstances."},
    {"title": "Kahaani", "genres": "Thriller", "overview": "A pregnant woman’s relentless search for her missing husband in Kolkata."},
    {"title": "My Name is Khan", "genres": "Drama/Romance", "overview": "A man with Asperger's embarks on a journey across the U.S. to prove his love and innocence."},
    {"title": "Yeh Jawaani Hai Deewani", "genres": "Romance/Drama", "overview": "Four friends navigate love and life through various stages and crossroads."},
    {"title": "Tumbbad", "genres": "Horror/Fantasy", "overview": "A mythical treasure leads a man on a dark and dangerous path in ancient India."},
    {"title": "Taare Zameen Par", "genres": "Family/Drama", "overview": "A dyslexic child finds support and confidence through his art teacher."},
    {"title": "Padmaavat", "genres": "Historical/Drama", "overview": "The story of Queen Padmavati, her husband Maharawal Ratan Singh, and Alauddin Khilji."},
    {"title": "Rockstar", "genres": "Romance/Musical", "overview": "A young musician finds success and heartbreak as he pursues his dreams."},
    {"title": "Bajrangi Bhaijaan", "genres": "Adventure/Drama", "overview": "An Indian man helps a mute Pakistani girl return to her homeland."},
    {"title": "Stree", "genres": "Horror/Comedy", "overview": "Villagers encounter a mysterious woman who abducts men during the night."},
    {"title": "Uri: The Surgical Strike", "genres": "Action/Drama", "overview": "Based on the true events of the Indian Army's surgical strikes in Pakistan-administered Kashmir."},
    {"title": "Article 15", "genres": "Crime/Drama", "overview": "An IPS officer investigates a caste-based crime that shakes up the community."},
    {"title": "Chak De! India", "genres": "Sports/Drama", "overview": "A disgraced hockey player coaches the Indian women's team to victory."},
    {"title": "Don", "genres": "Action/Thriller", "overview": "A police officer goes undercover to catch a notorious criminal, Don."},
    {"title": "Pink", "genres": "Social/Drama", "overview": "Three young women fight for justice against a powerful businessman in a legal battle."},
    {"title": "Drishyam", "genres": "Thriller", "overview": "A man goes to extreme lengths to protect his family from a crime they didn’t commit."},
    {"title": "Badhaai Ho", "genres": "Comedy/Drama", "overview": "A middle-aged couple’s unexpected pregnancy shocks their family and community."},
    {"title": "Jab We Met", "genres": "Romance/Comedy", "overview": "A bubbly woman and a heartbroken man embark on a journey that changes their lives."},
    {"title": "Bajirao Mastani", "genres": "Historical/Drama", "overview": "A love story of the Peshwa Bajirao and his second wife, Mastani, set in the Maratha Empire."},
    {"title": "Sui Dhaaga", "genres": "Drama/Inspirational", "overview": "A couple overcomes societal challenges to establish their own clothing business."},
    {"title": "Housefull", "genres": "Comedy", "overview": "A man with an unlucky love life tries to navigate through a series of humorous events."},
    {"title": "Munna Bhai M.B.B.S", "genres": "Comedy/Drama", "overview": "A thug enrolls in medical school to prove his worth to his parents."},
    {"title": "Haider", "genres": "Political Drama", "overview": "A young man returns to Kashmir and uncovers dark secrets about his family."},
    {"title": "Swades", "genres": "Drama", "overview": "An NRI returns to India and finds new purpose while trying to improve rural conditions."},
    {"title": "Ra.One", "genres": "Sci-Fi/Action", "overview": "A video game designer must fight against his creation, which has come to life."},
    {"title": "Veer-Zaara", "genres": "Romance/Drama", "overview": "A love story between an Indian Air Force officer and a Pakistani woman unfolds across borders."},
    {"title": "Bhool Bhulaiyaa", "genres": "Horror/Comedy", "overview": "A psychologist investigates strange events at an ancestral palace."},
    {"title": "KGF: Chapter 1", "genres": "Action/Drama", "overview": "A young man rises to power in the gold mines of Kolar, facing enemies and overcoming challenges to become a feared leader."},
    {"title": "Baahubali: The Conclusion", "genres": "Action/Fantasy", "overview": "In the epic finale, Mahendra Baahubali, son of Amarendra Baahubali, avenges his father's death and takes his rightful place as the king of Mahishmati."},
    {"title": "Vikram Vedha", "genres": "Action/Thriller", "overview": "A fearless cop chases down a notorious gangster, only to learn deeper lessons about morality and justice."},
    {"title": "Master", "genres": "Action/Thriller", "overview": "An alcoholic professor is assigned to teach in a juvenile correctional facility, where he encounters a dangerous criminal with a sinister agenda."},
    {"title": "Pushpa: The Rise", "genres": "Action/Drama", "overview": "Pushpa, a laborer in the red sandalwood smuggling trade, rises through the ranks amidst a dangerous syndicate."},
    {"title": "Kaithi", "genres": "Action/Thriller", "overview": "A prisoner, on his way to meet his daughter for the first time, is forced to help the police when a drug raid goes wrong."},
    {"title": "Sarkar", "genres": "Action/Drama", "overview": "A businessman returns to India and takes on corrupt politicians in his quest to clean up the system."},
    {"title": "Aruvi", "genres": "Action/Drama", "overview": "A young woman seeks vengeance against those who betrayed her, leading to a deep exploration of social issues."},
    {"title": "Ala Vaikunthapurramuloo", "genres": "Action/Drama", "overview": "A man raised by his mother in a modest family discovers the truth about his heritage and fights for his rightful place."},
    {"title": "Sye", "genres": "Action/Sports", "overview": "A unique action-sports drama where two rival college groups team up against a common enemy to save their playground."}
    ]



# Create a DataFrame from the list of dictionaries
df = pd.DataFrame(movies_data)

# Save DataFrame to a CSV file
df.to_csv('movies_list.csv', index=False)
